# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=100)),
                ('answer1', models.CharField(max_length=20)),
                ('answer2', models.CharField(max_length=20)),
                ('answer3', models.CharField(max_length=20)),
                ('answer4', models.CharField(max_length=20)),
                ('rightAnswer', models.CharField(choices=[('1', models.CharField(max_length=20)), ('2', models.CharField(max_length=20)), ('3', models.CharField(max_length=20)), ('4', models.CharField(max_length=20))], max_length=20)),
                ('difficulty', models.IntegerField()),
                ('topic', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
