# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0002_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='identification',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
